- name: download from azure
  include_role:
    name: artifacts-download-azure
  vars:
    artifact: "cassandra-backup-{{ artifact_version }}"
    artifact_path: /tmp
    artifacts_container: "{{ cassandra_backup_azure_container_name }}"

- name: extract the archive
  unarchive: src=/tmp/{{ artifact }} dest=/tmp remote_src=yes

- name: copy the restore script
  template: src=cassandra_restore.j2 dest=/tmp/cassandra_restore.py mode 0755

- set_fact:
    cassandra_backup_dir: /tmp/cassandra_backup

- name: Check doc_root path
  shell: ls -all {{ cassandra_backup_dir }}
  register: doc_data

- name: print doc_root to console
  debug:
    var: doc_data

- name: load the schema
  shell: cqlsh -f db_schema.cql
  args:
    chdir: "{{ cassandra_backup_dir }}"
  async: 3600
  poll: 10

- name: run the backup script
  shell: python cassandra_restore.py --host $(hostname -i) cassandra_backup
  args:
    chdir: /tmp
  async: 3600
  poll: 10
  
- name: clean up backup dir after upload
  file: path={{ cassandra_backup_dir }} state=absent
