env: sunbirddev
azure_storage_secret: "{{vault_azure_storage_secret}}"
azure_public_container: sunbird-content-dev
azure_account_name: sunbirddev
azure_account_key: "{{vault_azure_storage_secret}}"

secrets_path: '{{inventory_dir}}/secrets/lp_secrets.yml'

learner_user: learning
learner_group: learning
learner_user_home: "/home/{{ learner_user }}"

content_keyspace_name: "dev_content_store"
hierarchy_keyspace_name: "dev_hierarchy_store"
orchestrator_keyspace_name: "dev_script_store"

ecosystem_user: ecosystem
ecosystem_group: ecosystem  

instance: dev
instance_name: sunbird

content_media_base_url: https://dev.sunbirded.org      # content_media_base_url
plugin_media_base_url: https://dev.ekstep.in       # plugin_media_base_url
dial_service_search_url: https://dev.ekstep.in/api/dialcode/v3/search   # dial_service_search_url
content_to_vec_url: https://                             # content_to_vec_url
learning_content_h5p_library_path: https://s3.ap-south-1.amazonaws.com/ekstep-public-dev/content/templates/h5p-library-latest.zip            # learning_content_h5p_library_path


neo4j_dir: neo4j-learning
neo4j_home: "{{learner_user_home}}/{{neo4j_dir}}/neo4j-enterprise-3.3.0"
neo4j_zip: neo4j-enterprise-3.3.0-unix.tar.gz       # neo4j enterprise version.zip 
zip_file: learning-graph-extension-1.0.jar
custom_procs_file: custom-procedures-1.0.jar
neo4j_enterprise: "true"
orchestrator_url: 

hadoop_version: 2.7.2
resourcemanager: "{{ groups['lp-yarn-master'][0] }}"
yarn_slaves: "{{ groups['lp-yarn-slave']}}"
__yarn_host__: "{{ groups['lp-yarn-master'][0] }}"
__yarn_port__: 8000
env_name: "{{ env }}"
kafka_brokers: "{{groups['processing-cluster-kafka']|join(':9092,')}}:9092"
zookeepers: "{{groups['zookeeper']|join(':2181,')}}:2181"
delayInMilliSeconds: 60000
retryTimeInMilliSeconds: 10000
retry_backoff_base_in_seconds: 10
bypass_reverse_search: true
retry_limit: 4
retry_limit_enable: true
google_api_key: "123"
audit_es_host: "{{ groups['composite-search-cluster']|join(':9200,')}}:9200"
search_es_host: "{{ groups['composite-search-cluster']|join(':9200,')}}:9200"
redis_host: "{{ groups['redis1'][0] }}"
redis_port: 6379
search_service_endpoint: https://dev.ekstep.in/api/search/v2/search
environment_id: 10000000
graph_passport_key: "{{ vault_graph_passport_key }}"
lp_bolt_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
lp_bolt_read_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
lp_bolt_write_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
lp_url: http://{{ groups['learning1'][0] }}:8080/learning-service
lp_tmpfile_location: /tmp
language_url: http://{{ groups['learning1'][0] }}:8080/language-service
other_bolt_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:8687
other_bolt_read_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:8687
other_bolt_write_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:8687
tr_secondary_route_events: "LOG,ERROR"
mw_shard_id: 1
google_vision_tagging: false
es_port: 9200
cassandra_host:  "{{ groups['lp-cassandra'][0] }}"
cassandra_port: 9042
content_keyspace_name: "dev_content_store"
content_keyspace_table: content_data
s3_public_bucket: ""
collection_fullecar_disable: true
max_iteration_count_for_samza_job: 2
composite_search_indexer_container_count: 1
cloud_store: azure
default_channel: "01250894314817126443"
publish_invoke_web_hook: false
cloud_storage_config_environment: "{{env}}"
dial_service_generate_url: https://dev.ekstep.in/api/dialcode/v3/generate

learnings:
  paths: ['/data', '/data/graphDB', '/data/logs', '/data/contentBundle', '/data/properties', '/home/learning/tmp', '/home/learning/platform']
  service_config: ['consumer-config.xml']

searchs:
  paths: ['/data', '/data/logs', '/data/contentBundle', '/data/properties', '/home/learning/tmp', '/home/learning/platform', '/home/learning/platform/search', '/home/learning/platform/service', '/home/learning/platform/service/logs' ]


cassandra_lp_connection: "{{groups['cassandra-cluster']|join(':9042,')}}:9042"
cassandra_lpa_connection: "{{ groups['dp-cassandra'][0] }}:9042"
cassandra_sunbird_connection: "{{ groups['dev-cassandra-1'][0] }}:9042"
cloud_upload_retry_count: 3
streaming_mime_type: "video/mp4,video/webm"

# to be depricated
content_to_vec_url: ""

compositesearch_index_name: "compositesearch"

secor_azure_container_name: "telemetry-data-store"

secor:
  properties: ['secor.azure', 'secor.common', 'secor', 'secor.partition', 'log4j']
  artifact_dir: /mount/secor
  s3:
    bucket: "dev-data-store"
    #aws_key: "{{vault_aws_key}}"
    #aws_secret: "{{vault_aws_secret}}"
  azure:
    account_name: "sunbirddevtelemetry"
    account_key: "{{ vault_azure_account_key }}"
    container_name: "dev-data-store"
  paths: ['/mount/secor', '/mount/secor/reports', '/mount/secor/logs', '/home/analytics/sbin', '/mount/data/analytics']
  channel: "#sunbird-dp-dev-alerts"
